name: 'Cloud Resume Challenge Testing and Infrastructure Deployment'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'Backend/**'

env:
  TF_VAR_dynamodb_table_name: ${{ env.dynamodb_table_name }}
  TF_VAR_dynamodb_partition_key: ${{ env.dynamodb_partition_key }} 
  TF_VAR_current_count_number: ${{ env.current_count_number }} 
  TF_VAR_s3_lambda_function_bucket : ${{ env.s3_lambda_function_bucket }} 
  TF_VAR_s3_key_lambda_function_file : ${{ env.s3_key_lambda_function_file }} 
  TF_VAR_domain_name : ${{ env.domain_name }} 


jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3.5.3

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2.0.3

      - name: 'Terraform Init'
        run: |
          cd Backend
          terraform init

      - name: 'Terraform Validate'
        run: |
          cd Backend
          terraform validate

      - name: 'Terraform Plan'
        run: |
          cd Backend
          terraform plan
