name: 'Cloud Resume Challenge Testing and Infrastructure Deployment'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'Backend/**'

      
jobs:
  Lambda-Testing:
    runs-on: ubuntu-latest
    name: Perform lambda backend unit test 
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Python Dependency Installation
        run: |
          python3 -m pip install --upgrade pip
          pip3 install unittest moto
      - name: Run unit test
        run: |
          python3 visitor-counter-test.py 

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3.5.3

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2.0.3

      - name: 'Terraform Init'
        run: |
          cd Backend
          terraform init -backend-config="bucket=$TF_STATE_S3" -backend-config="region=$AWS_REGION" -backend-config="key=$TF_STATE_S3_KEY" -backend-config="dynamodb_table=$TF_DB_LOCK" -backend-config="encrypt=true"
        env:
            AWS_REGION: 'us-west-2'
            TF_STATE_S3: ${{ secrets.TF_STATE_S3 }}
            TF_STATE_S3_KEY: ${{ secrets.TF_STATE_S3_KEY }}
            TF_DB_LOCK: ${{ secrets.TF_DB_LOCK }}


      - name: 'Terraform Validate'
        run: |
          cd Backend
          terraform validate

      - name: 'Terraform Plan'
        run: |
          cd Backend
          terraform plan
