name: 'Cloud Resume Challenge Testing and Infrastructure Deployment'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'Backend/**'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3.5.3

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2.0.3

      - name: 'Terraform Init'
        run: |
          cd Backend
          terraform init

      - name: 'Terraform Validate'
        run: |
          cd Backend
          terraform validate

      - name: 'Terraform Plan'
        run: |
          cd Backend
          terraform plan
